// This file was autogenerated by ../../libs/closure-library-20130212-95c19e7f0f5f/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../libs/utils.js/src/Log.js', ['andrzejdus.utils.Log'], []);
goog.addDependency('../../../../libs/utils.js/src/Looper.js', ['andrzejdus.utils.Looper'], []);
goog.addDependency('../../../../libs/utils.js/src/Utils.js', ['andrzejdus.utils.Utils'], []);
goog.addDependency('../../../../libs/utils.js/src/events/EventManager.js', ['andrzejdus.utils.events.EventManager'], []);
goog.addDependency('../../../../libs/utils.js/src/events/EventsManager.js', ['andrzejdus.utils.events.EventsManager'], ['andrzejdus.utils.events.EventManager']);
goog.addDependency('../../../../src/Parallaxer.js', ['andrzejdus.parallaxer.Parallaxer'], ['andrzejdus.parallaxer.ParallaxerEvent', 'andrzejdus.parallaxer.drawer.Drawer', 'andrzejdus.utils.Log', 'andrzejdus.utils.Looper', 'andrzejdus.utils.Utils', 'andrzejdus.utils.events.EventsManager']);
goog.addDependency('../../../../src/ParallaxerEvent.js', ['andrzejdus.parallaxer.ParallaxerEvent'], []);
goog.addDependency('../../../../src/drawer/Cache.js', ['andrzejdus.parallaxer.drawer.Cache'], []);
goog.addDependency('../../../../src/drawer/Drawer.js', ['andrzejdus.parallaxer.drawer.Drawer'], ['andrzejdus.parallaxer.drawer.Cache', 'andrzejdus.parallaxer.drawer.DrawerObject', 'andrzejdus.parallaxer.drawer.VisibilityChecker', 'andrzejdus.utils.Log']);
goog.addDependency('../../../../src/drawer/DrawerObject.js', ['andrzejdus.parallaxer.drawer.DrawerObject'], []);
goog.addDependency('../../../../src/drawer/VisibilityChecker.js', ['andrzejdus.parallaxer.drawer.VisibilityChecker'], []);
goog.addDependency('../../../../tests/parallaxer_1/src/js/Main.js', ['test.Main'], ['andrzejdus.parallaxer.Parallaxer']);
