// This file was autogenerated by ../../../../libs-external/closure-library-20120710-r2029/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../libs-andrzejdus/parallaxer.js/src/ScrollParallaxer.js', ['andrzejdus.parallaxer.ScrollParallaxer'], ['andrzejdus.parallaxer.ScrollParallaxerEvent', 'andrzejdus.parallaxer.drawer.Drawer', 'andrzejdus.utils.AnimationFrame', 'andrzejdus.utils.Log', 'andrzejdus.utils.Utils', 'andrzejdus.utils.events.EventsManager']);
goog.addDependency('../../../../libs-andrzejdus/parallaxer.js/src/ScrollParallaxerEvent.js', ['andrzejdus.parallaxer.ScrollParallaxerEvent'], []);
goog.addDependency('../../../../libs-andrzejdus/parallaxer.js/src/drawer/Cache.js', ['andrzejdus.parallaxer.drawer.Cache'], []);
goog.addDependency('../../../../libs-andrzejdus/parallaxer.js/src/drawer/Drawer.js', ['andrzejdus.parallaxer.drawer.Drawer'], ['andrzejdus.parallaxer.drawer.Cache', 'andrzejdus.parallaxer.drawer.DrawerObject', 'andrzejdus.parallaxer.drawer.VisibilityChecker', 'andrzejdus.utils.Log']);
goog.addDependency('../../../../libs-andrzejdus/parallaxer.js/src/drawer/DrawerObject.js', ['andrzejdus.parallaxer.drawer.DrawerObject'], []);
goog.addDependency('../../../../libs-andrzejdus/parallaxer.js/src/drawer/VisibilityChecker.js', ['andrzejdus.parallaxer.drawer.VisibilityChecker'], []);
goog.addDependency('../../../../libs-andrzejdus/utils/src/AnimationFrame.js', ['andrzejdus.utils.AnimationFrame'], []);
goog.addDependency('../../../../libs-andrzejdus/utils/src/Log.js', ['andrzejdus.utils.Log'], []);
goog.addDependency('../../../../libs-andrzejdus/utils/src/Utils.js', ['andrzejdus.utils.Utils'], []);
goog.addDependency('../../../../libs-andrzejdus/utils/src/events/EventManager.js', ['andrzejdus.utils.events.EventManager'], []);
goog.addDependency('../../../../libs-andrzejdus/utils/src/events/EventsManager.js', ['andrzejdus.utils.events.EventsManager'], ['andrzejdus.utils.events.EventManager']);
goog.addDependency('js/Main.js', ['test.Main'], ['andrzejdus.parallaxer.ScrollParallaxer']);
